### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [lmj0011/save-on-device#1]
This seems like a real useful little tool – a pity it's only installable via Google's walled garden. Would you mind making it available for users without access to the Playstore? Like, [tagging releases](https://github.com/lmj0011/save-on-device/releases) and attaching the APK there, or have your app built and listed by [F-Droid](https://f-droid.org/)?

**Comment by lmj0011** [comment]
>PS: If you want the app's metadata (summary, description, icon, featureGraphic etc) in Fastlane structures for easy maintenance, just let me know. I've set that up for my repo anyway, so I can easily prepare a PR with that.

Sure, whenever you have the time.

@IzzySoft

**Comment by IzzySoft** [comment]
Done, see #5 (you waited almost too long; as your app already entered F-Droid, it was already removed from my repo. Good thing I always archive metadata then :smile:) Enjoy!
