### ISSUE TITLE
Inclusion on F-droid

### ISSUE THREAD

**Issue by proletarius101** [lmj0011/save-on-device#2]
I've made a fdroid build recipe for this Save on Device app since I find it really useful: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10077

Do you agree that we list it on f-droid.org?

**Comment by lmj0011** [comment]
@proletarius101 

sure, go for it.

**Comment by lmj0011** [comment]
ref: https://gitlab.com/fdroid/rfp/-/issues/1908
