### ISSUE TITLE
support of min_sdk 21 (android 5.0)

### ISSUE THREAD

**Issue by DI555** [lmj0011/save-on-device#6]
please, is it possible to add min_sdk 21 (android 5.0) support,
or at least min_sdk 22 (android 5.1) it not possible first.
great thanks in advance.

**Comment by lmj0011** [comment]
>Direct Share was introducted in Android 6.0 (API level 23) allowing apps to provide ChooserTarget objects through a ChooserTargetService. Results were retrieved reactively on demand, leading to a slow loading time for targets.

Not possible, min_sdk will stay 23.

https://developer.android.com/training/sharing/receive.html#providing-direct-share-targets
